const uiText = {
  en: {
    siteTitle: "Fruits & Vegetables",
    siteSubtitle: "Employee help book",
    products: "Products",
    addProduct: "Add Product",
    search: "Search products...",
    description: "Description",
    what: "What it is",
    healthy: "Why it is healthy",
    eat: "How to eat it",
    back: "← Back",
    allProducts: "← All Products",
    notFound: "Product not found",
    errorLoading: "Error loading product",
    errorLoadingProducts: "Error loading products.",
    mainCode: "1C code",
    discountCode: "Discount code",
    scaleCode: "Scale code",
    scaleDiscountCode: "Scale discount code",
    noProducts: "No products found.",
    name: "Product name",
    image: "Product image",
    needsScale: "Needs scale",
    save: "Save Product",
    chooseImage: "Please choose an image.",
    saved: "Product saved successfully!",
    names: "Names",
    nameEn: "Product name (EN)",
    nameHy: "Product name (HY)",
    nameRu: "Product name (RU)",
    descriptionEn: "Description (EN)",
    descriptionHy: "Description (HY)",
    descriptionRu: "Description (RU)",
    whatPlaceholder: "What is it?",
    healthyPlaceholder: "Why is it healthy?",
    eatPlaceholder: "How to eat it? (one item per line)",
    english: "English",
    armenian: "Armenian",
    russian: "Russian"
  },
  hy: {
    siteTitle: "Մրգեր և Բանջարեղեն",
    siteSubtitle: "Աշխատակիցների օգնության գիրք",
    products: "Ապրանքներ",
    addProduct: "Ավելացնել ապրանք",
    search: "Որոնել ապրանքներ...",
    description: "Նկարագրություն",
    what: "Ի՞նչ է սա",
    healthy: "Ինչո՞վ է օգտակար",
    eat: "Ինչպե՞ս օգտագործել",
    back: "← Հետ",
    allProducts: "← Բոլոր ապրանքները",
    notFound: "Ապրանքը չի գտնվել",
    errorLoading: "Սխալ՝ ապրանքը բեռնելիս",
    errorLoadingProducts: "Սխալ՝ ապրանքները բեռնելիս։",
    mainCode: "1C կոդ",
    discountCode: "Զեղչի կոդ",
    scaleCode: "Կշեռքի կոդ",
    scaleDiscountCode: "Կշեռքի զեղչի կոդ",
    noProducts: "Ապրանքներ չեն գտնվել։",
    name: "Ապրանքի անուն",
    image: "Ապրանքի նկար",
    needsScale: "Պետք է կշեռք",
    save: "Պահպանել ապրանքը",
    chooseImage: "Խնդրում ենք ընտրել նկար։",
    saved: "Ապրանքը հաջողությամբ պահպանվեց։",
    names: "Անվանումներ",
    nameEn: "Ապրանքի անունը (EN)",
    nameHy: "Ապրանքի անունը (HY)",
    nameRu: "Ապրանքի անունը (RU)",
    descriptionEn: "Նկարագրություն (EN)",
    descriptionHy: "Նկարագրություն (HY)",
    descriptionRu: "Նկարագրություն (RU)",
    whatPlaceholder: "Ի՞նչ է սա",
    healthyPlaceholder: "Ինչո՞վ է օգտակար",
    eatPlaceholder: "Ինչպե՞ս օգտագործել (յուրաքանչյուր տարբերակը՝ նոր տողում)",
    english: "Անգլերեն",
    armenian: "Հայերեն",
    russian: "Ռուսերեն"
  },
  ru: {
    siteTitle: "Фрукты и Овощи",
    siteSubtitle: "Справочник для сотрудников",
    products: "Продукты",
    addProduct: "Добавить продукт",
    search: "Поиск продуктов...",
    description: "Описание",
    what: "Что это",
    healthy: "Чем полезно",
    eat: "Как употреблять",
    back: "← Назад",
    allProducts: "← Все продукты",
    notFound: "Продукт не найден",
    errorLoading: "Ошибка загрузки продукта",
    errorLoadingProducts: "Ошибка загрузки продуктов.",
    mainCode: "1C код",
    discountCode: "Код скидки",
    scaleCode: "Код весов",
    scaleDiscountCode: "Код скидки весов",
    noProducts: "Продукты не найдены.",
    name: "Название продукта",
    image: "Изображение продукта",
    needsScale: "Нужны весы",
    save: "Сохранить продукт",
    chooseImage: "Пожалуйста, выберите изображение.",
    saved: "Продукт успешно сохранён.",
    names: "Названия",
    nameEn: "Название продукта (EN)",
    nameHy: "Название продукта (HY)",
    nameRu: "Название продукта (RU)",
    descriptionEn: "Описание (EN)",
    descriptionHy: "Описание (HY)",
    descriptionRu: "Описание (RU)",
    whatPlaceholder: "Что это",
    healthyPlaceholder: "Чем полезно",
    eatPlaceholder: "Как употреблять? (по одному варианту на строку)",
    english: "Английский",
    armenian: "Армянский",
    russian: "Русский"
  }
};